site_name: LCLS Users Documentation
repo_url: https://github.com/lcls-users/lcls-users
site_author: FP, AP, GFD
copyright: © 2023 LCLS
markdown_extensions:
    - admonition
    - attr_list
    - def_list
nav:
    - Before your experiment:
        - Computing Accounts and Resources: 'before/accounts.md'
        - Routine beamtime analysis: 'before/analysis.md'
    - During your experiment:
        - Running the timetool: 'during/timetool.md'
    - After your experiment:
        - Reanalyzing timing data: 'after/timetool.md'
    - Tutorials:
          - How to computers: 'tutorials/computers101.md'
    - Miscellaneous:
        - Troubleshooting: 'troubleshooting.md'
        - Glossary: 'glossary.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
    collapse_navigation: false
    navigation_depth: 3
    titles_only: true
